### ISSUE TITLE
check-runner.js fails on HTTPS error for some reason sometimes

### ISSUE THREAD

**Issue by kltm** [geneontology/shared-annotation-check#6]
The script started failing with the error:
```
16:31:44  + node ./check-runner.js -i ./rules.txt -o /var/lib/jenkins/workspace/logy_pipeline_snapshot-post-fail/mnt/snapshot/reports/shared-annotation-check.html
16:31:44  ERROR in sync_request call, will try to recover
16:31:44  /var/lib/jenkins/workspace/logy_pipeline_snapshot-post-fail/shared-annotation-check/node_modules/bbop-response-golr/lib/response.js:224
16:31:44      return parseInt(robj.response.numFound);
16:31:44                           ^
16:31:44  
16:31:44  TypeError: Cannot read property 'response' of undefined
16:31:44      at response.total_documents (/var/lib/jenkins/workspace/logy_pipeline_snapshot-post-fail/shared-annotation-check/node_modules/bbop-response-golr/lib/response.js:224:26)
16:31:44      at /var/lib/jenkins/workspace/logy_pipeline_snapshot-post-fail/shared-annotation-check/check-runner.js:251:22
```

After some(!) digging, it turns out to have something to do with SSL cert handling and expiration on golr-aux.geneontology.io, but I can't quite figure out what it is as it is setup _exactly_ the same way as the working golr.geneontology.org. 
That said, even in a browser, where there is no error, the cert reports as a non-expired LE, instead of Cloudflare, which should not happen. Odd.

To reproduce to failure:

```
> var request = require('sync-request');
> var res = request('POST', 'https://golr-aux.geneontology.io/solr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&q=*:*')
Error: certificate has expired
    at doRequest (/srv/shared-annotation-check/node_modules/sync-request/index.js:31:11)
```

**Comment by kltm** [comment]
I'm just going to change the server endpoint for the moment.

**Comment by kltm** [comment]
Okay, the server endpoint change did not work as in testing. In fact, the local testing is now failing. Digging in, but in discussion with @pgaudet this morning, if I can't get this to work by the end of the day, I'm going to remove it from the pipeline so we can proceed.

**Comment by kltm** [comment]
Okay, I think I may have found the origin of this, and have tested a fix locally.
Basically, there is an SSL cert cache that exists on machines that, in some cases apparently, can get "stuck".
Running the following command locally:
```
sudo update-ca-certificates --fresh
```
got the original URL working again, without the SSL cert error. Looking at the edge certs in cloudflare, there seems to have been a let's encrypt / google cert transition recently? I'm not sure what the originating trigger was, but I'm happy to call this wrapped for the moment.

One final note: just after all of the above, uptimerobot started giving SSL cert expiration errors that seem local to it, and are the older cert. I wonder if they got hit by the same thing as me?
